### ISSUE TITLE
High CPU usage and disk writes since last update

### ISSUE THREAD

**Issue by domolys** [home-assistant/plugin-audio#53]
supervisor-2021.02.11
with hassio_audio-2021.02.1
on Debian 10 (Buster) Supervised installation

I have to shutdown my installation because of high CPU usage and disk writes of more than 10GB /day comming from hassio_audio container

CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O        BLOCK I/O        PIDS
a08c5d65bbc2   hassio_audio   20.66%    0B / 0B             0.00%     875kB / 685B   10.5MB / 786MB   7

Would like to debug with pactl but also got this:

# pactl list
**Connection failure: Connection refused
pa_context_connect() failed: Connection refused**

**Comment by metropt** [comment]
I have the same problem. In my case my system is unsupported:
![image](https://user-images.githubusercontent.com/764040/108565383-7d090400-72fc-11eb-82b1-261b8fe25aad.png)
![image](https://user-images.githubusercontent.com/764040/108565407-885c2f80-72fc-11eb-8f55-b17728893656.png)

**Comment by metropt** [comment]
After some docker restart and host reboot it is now stable at 20%
![image](https://user-images.githubusercontent.com/764040/108610917-86b06b80-73d1-11eb-8766-2ff37541b8be.png)

**Comment by logicup-dev** [comment]
Please note that after a fresh re-install of Debian, apt update apt upgrade, reinstall and restore ha, now everything looks good.

I can provide Audio logs if necessary, now the log is better...;) ... also got to stop running old installation because of Audio Add-on CPU usage and disk writes...

docker stats after re-install:

`NAME                                        CPU %     MEM %     BLOCK I/O
addon_a0d7b954_bookstack                    0.01%     1.25%     881kB / 168kB
addon_cebe7a76_hassio_google_drive_backup   0.75%     0.43%     0B / 0B
addon_core_nginx_proxy                      0.00%     0.07%     0B / 16.4kB
addon_core_configurator                     0.03%     0.55%     21.6MB / 12.3kB
addon_core_ssh                              0.00%     0.86%     24.1MB / 8.09MB
addon_core_mariadb                          0.15%     3.20%     39.1MB / 110MB
addon_core_mosquitto                        0.09%     0.86%     6.47MB / 8.19kB
hassio_multicast                            0.00%     0.11%     4.08MB / 16.4kB
hassio_cli                                  0.00%     0.03%     90.1kB / 0B
hassio_audio                                0.00%     0.87%     12.8MB / 57.3kB
hassio_dns                                  0.05%     0.43%     22.5MB / 20.5kB
homeassistant                               0.20%     3.08%     8.09MB / 221kB
hassio_observer                             0.00%     0.38%     13.2MB / 4.1kB
hassio_supervisor                           0.00%     3.18%     48.5MB / 618kB`

**Comment by femike** [comment]
I have the same problem too, on my Raspbian GNU/Linux 10 (buster)

```bash
CONTAINER ID   NAME                               CPU %     MEM USAGE / LIMIT   MEM %     NET I/O           BLOCK I/O   PIDS
cb6ec126d315   addon_core_configurator            0.05%     0B / 0B             0.00%     105kB / 0B        0B / 0B     4
94b87b591096   addon_a0d7b954_phpmyadmin          0.01%     0B / 0B             0.00%     112kB / 3.99kB    0B / 0B     10
e34962848c75   addon_a0d7b954_nginxproxymanager   0.04%     0B / 0B             0.00%     11.3MB / 10.2MB   0B / 0B     22
9869683c37f7   addon_a0d7b954_glances             1.00%     0B / 0B             0.00%     0B / 0B           0B / 0B     23
6e2577bde933   addon_core_duckdns                 0.01%     0B / 0B             0.00%     197kB / 11.9kB    0B / 0B     7
52a10900368e   addon_core_mariadb                 0.63%     0B / 0B             0.00%     1.86MB / 1.47MB   0B / 0B     39
5f7b4798a4a7   hassio_multicast                   0.58%     0B / 0B             0.00%     0B / 0B           0B / 0B     4
185bf4b0a51a   hassio_cli                         0.00%     0B / 0B             0.00%     162kB / 0B        0B / 0B     5
a4ab11fb1d0a   hassio_audio                       25.74%    0B / 0B             0.00%     162kB / 0B        0B / 0B     7
de129e6b969c   hassio_dns                         1.38%     0B / 0B             0.00%     196kB / 58.7kB    0B / 0B     13
60383910bb8d   hassio_observer                    0.00%     0B / 0B             0.00%     168kB / 1.45kB    0B / 0B     8
f597f83a9741   hassio_supervisor                  9.46%     0B / 0B             0.00%     6.64MB / 6.95MB   0B / 0B     16
0d1805af843e   homeassistant                      3.10%     0B / 0B             0.00%     0B / 0B           0B / 0B     17
```
$ ha audio logs

```bash
W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
D: [pulseaudio] core-rtclock.c: Timer slack is set to 50 us.
D: [pulseaudio] core-util.c: setpriority() worked.
I: [pulseaudio] core-util.c: Successfully gained nice level -11.
I: [pulseaudio] main.c: Found user 'root' (UID 0) and group 'root' (GID 0).
W: [pulseaudio] main.c: Home directory of user 'root' is not '/var/run/pulse', ignoring.
W: [pulseaudio] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
I: [pulseaudio] main.c: Successfully changed user to "root".
I: [pulseaudio] main.c: This is PulseAudio 14.2
D: [pulseaudio] main.c: Compilation CFLAGS: Not yet supported on meson
D: [pulseaudio] main.c: Running on host: Linux armv7l 5.10.11-v7+ #1399 SMP Thu Jan 28 12:06:05 GMT 2021
D: [pulseaudio] main.c: Found 4 CPUs.
I: [pulseaudio] main.c: Page size is 4096 bytes
D: [pulseaudio] main.c: Compiled with Valgrind support: no
D: [pulseaudio] main.c: Running in valgrind mode: no
D: [pulseaudio] main.c: Running in VM: no
D: [pulseaudio] main.c: Running from build tree: no
D: [pulseaudio] main.c: Optimized build: yes
D: [pulseaudio] main.c: All asserts enabled.
I: [pulseaudio] main.c: Machine ID is 9a6ad1d4e04c41d88eb68eca20408ea2.
I: [pulseaudio] main.c: Using runtime directory /var/run/pulse.
I: [pulseaudio] main.c: Using state directory /data/states.
I: [pulseaudio] main.c: Using modules directory /usr/lib/pulse-14.2/modules.
I: [pulseaudio] main.c: Running in system mode: yes
W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please make sure that you actually do want to do that.
W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.
W: [pulseaudio] pid.c: Stale PID file, overwriting.
I: [pulseaudio] main.c: System supports high resolution timers
D: [pulseaudio] memblock.c: Using private memory pool with 1024 slots of size 64.0 KiB each, total size is 64.0 MiB, maximum usable slot size is 65496
I: [pulseaudio] cpu-arm.c: CPU flags: V6 V7 VFP EDSP NEON VFPV3 
I: [pulseaudio] svolume_arm.c: Initialising ARM optimized volume functions.
I: [pulseaudio] sconv_neon.c: Initialising ARM NEON optimized conversions.
I: [pulseaudio] mix_neon.c: Initialising ARM NEON optimized mixing functions.
I: [pulseaudio] remap_neon.c: Initialising ARM NEON optimized remappers.
D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/9a6ad1d4e04c41d88eb68eca20408ea2-device-volumes.tdb'
I: [pulseaudio] database.c: Successfully opened 'device-volumes' database file '/data/states/9a6ad1d4e04c41d88eb68eca20408ea2-device-volumes.tdb'.
I: [pulseaudio] module.c: Loaded "module-device-restore" (index: #0; argument: "").
D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/9a6ad1d4e04c41d88eb68eca20408ea2-stream-volumes.tdb'
I: [pulseaudio] database.c: Successfully opened 'stream-volumes' database file '/data/states/9a6ad1d4e04c41d88eb68eca20408ea2-stream-volumes.tdb'.
D: [pulseaudio] protocol-dbus.c: Interface org.PulseAudio.Ext.StreamRestore1 added for object /org/pulseaudio/stream_restore1
I: [pulseaudio] module.c: Loaded "module-stream-restore" (index: #1; argument: "").
D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/9a6ad1d4e04c41d88eb68eca20408ea2-card-database.tdb'
I: [pulseaudio] database.c: Successfully opened 'card-database' database file '/data/states/9a6ad1d4e04c41d88eb68eca20408ea2-card-database.tdb'.
I: [pulseaudio] module.c: Loaded "module-card-restore" (index: #2; argument: "").
I: [pulseaudio] module.c: Loaded "module-switch-on-port-available" (index: #3; argument: "").
I: [pulseaudio] module.c: Loaded "module-switch-on-connect" (index: #4; argument: "").
D: [pulseaudio] module-udev-detect.c: /dev/snd/controlC0 is accessible: yes
W: [pulseaudio] module-udev-detect.c: Failed to open /proc/asound/card0: No such file or directory
D: [pulseaudio] module-udev-detect.c: /devices/platform/soc/3f00b840.mailbox/bcm2835_audio/sound/card0 is busy: no
E: [pulseaudio] core-rtclock.c: Assertion 'clock_gettime(CLOCK_REALTIME, &ts) == 0' failed at ../src/pulsecore/core-rtclock.c:93, function pa_rtclock_get(). Aborting.
```

problem with pulseaudio, alsa start ok and found device, i try run alsamixer in container and they run correctly.

**Comment by Dominik-1980** [comment]
Please have a look what I have figured out here...

https://community.home-assistant.io/t/hassio-audio-is-in-boot-loop-and-spams-my-syslog-with-errors/282538/44

**Comment by deluxestyle** [comment]
I‘m facing the same problem. With exact the same logs

**Comment by metropt** [comment]
`W: [pulseaudio] pid.c: Stale PID file, overwriting.
I: [pulseaudio] main.c: System supports high resolution timers
D: [pulseaudio] memblock.c: Using private memory pool with 1024 slots of size 64.0 KiB each, total size is 64.0 MiB, maximum usable slot size is 65496
I: [pulseaudio] cpu-arm.c: CPU flags: V6 V7 VFP EDSP NEON VFPV3
I: [pulseaudio] svolume_arm.c: Initialising ARM optimized volume functions.
I: [pulseaudio] sconv_neon.c: Initialising ARM NEON optimized conversions.
I: [pulseaudio] mix_neon.c: Initialising ARM NEON optimized mixing functions.
I: [pulseaudio] remap_neon.c: Initialising ARM NEON optimized remappers.
D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-device-volumes.tdb'
I: [pulseaudio] database.c: Successfully opened 'device-volumes' database file '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-device-volumes.tdb'.
I: [pulseaudio] module.c: Loaded "module-device-restore" (index: #0; argument: "").
D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-stream-volumes.tdb'
I: [pulseaudio] database.c: Successfully opened 'stream-volumes' database file '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-stream-volumes.tdb'.
D: [pulseaudio] protocol-dbus.c: Interface org.PulseAudio.Ext.StreamRestore1 added for object /org/pulseaudio/stream_restore1
I: [pulseaudio] module.c: Loaded "module-stream-restore" (index: #1; argument: "").
D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-card-database.tdb'
I: [pulseaudio] database.c: Successfully opened 'card-database' database file '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-card-database.tdb'.
I: [pulseaudio] module.c: Loaded "module-card-restore" (index: #2; argument: "").
I: [pulseaudio] module.c: Loaded "module-switch-on-port-available" (index: #3; argument: "").
I: [pulseaudio] module.c: Loaded "module-switch-on-connect" (index: #4; argument: "").
D: [pulseaudio] module-udev-detect.c: Ignoring /devices/platform/ff500000.usb/usb3/3-1/3-1:1.0/sound/card1, because marked so.
D: [pulseaudio] module-udev-detect.c: /dev/snd/controlC0 is accessible: yes
W: [pulseaudio] module-udev-detect.c: Failed to open /proc/asound/card0: No such file or directory
D: [pulseaudio] module-udev-detect.c: /devices/platform/sound/sound/card0 is busy: no
E: [pulseaudio] core-rtclock.c: Assertion 'clock_gettime(CLOCK_REALTIME, &ts) == 0' failed at ../src/pulsecore/core-rtclock.c:93, function pa_rtclock_get(). Aborting.
W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
D: [pulseaudio] core-rtclock.c: Timer slack is set to 50 us.
D: [pulseaudio] core-util.c: setpriority() worked.
I: [pulseaudio] core-util.c: Successfully gained nice level -11.
I: [pulseaudio] main.c: Found user 'root' (UID 0) and group 'root' (GID 0).
W: [pulseaudio] main.c: Home directory of user 'root' is not '/var/run/pulse', ignoring.
W: [pulseaudio] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
I: [pulseaudio] main.c: Successfully changed user to "root".
I: [pulseaudio] main.c: This is PulseAudio 14.2
D: [pulseaudio] main.c: Compilation CFLAGS: Not yet supported on meson
D: [pulseaudio] main.c: Running on host: Linux armv7l 5.10.16-rockchip #21.02.2 SMP PREEMPT Sun Feb 14 23:02:55 CET 2021
D: [pulseaudio] main.c: Found 4 CPUs.
I: [pulseaudio] main.c: Page size is 4096 bytes
D: [pulseaudio] main.c: Compiled with Valgrind support: no
D: [pulseaudio] main.c: Running in valgrind mode: no
D: [pulseaudio] main.c: Running in VM: no
D: [pulseaudio] main.c: Running from build tree: no
D: [pulseaudio] main.c: Optimized build: yes
D: [pulseaudio] main.c: All asserts enabled.
I: [pulseaudio] main.c: Machine ID is 4bb2d1b22b6b4897ab74971dd8ba1cf1.
I: [pulseaudio] main.c: Using runtime directory /var/run/pulse.
I: [pulseaudio] main.c: Using state directory /data/states.
I: [pulseaudio] main.c: Using modules directory /usr/lib/pulse-14.2/modules.
I: [pulseaudio] main.c: Running in system mode: yes
W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please make sure that you actually do want to do that.
W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.
W: [pulseaudio] pid.c: Stale PID file, overwriting.
I: [pulseaudio] main.c: System supports high resolution timers
D: [pulseaudio] memblock.c: Using private memory pool with 1024 slots of size 64.0 KiB each, total size is 64.0 MiB, maximum usable slot size is 65496
I: [pulseaudio] cpu-arm.c: CPU flags: V6 V7 VFP EDSP NEON VFPV3
I: [pulseaudio] svolume_arm.c: Initialising ARM optimized volume functions.
I: [pulseaudio] sconv_neon.c: Initialising ARM NEON optimized conversions.
I: [pulseaudio] mix_neon.c: Initialising ARM NEON optimized mixing functions.
I: [pulseaudio] remap_neon.c: Initialising ARM NEON optimized remappers.
D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-device-volumes.tdb'
I: [pulseaudio] database.c: Successfully opened 'device-volumes' database file '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-device-volumes.tdb'.
I: [pulseaudio] module.c: Loaded "module-device-restore" (index: #0; argument: "").
D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-stream-volumes.tdb'
I: [pulseaudio] database.c: Successfully opened 'stream-volumes' database file '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-stream-volumes.tdb'.
D: [pulseaudio] protocol-dbus.c: Interface org.PulseAudio.Ext.StreamRestore1 added for object /org/pulseaudio/stream_restore1
I: [pulseaudio] module.c: Loaded "module-stream-restore" (index: #1; argument: "").
D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-card-database.tdb'
I: [pulseaudio] database.c: Successfully opened 'card-database' database file '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-card-database.tdb'.
I: [pulseaudio] module.c: Loaded "module-card-restore" (index: #2; argument: "").
I: [pulseaudio] module.c: Loaded "module-switch-on-port-available" (index: #3; argument: "").
I: [pulseaudio] module.c: Loaded "module-switch-on-connect" (index: #4; argument: "").
D: [pulseaudio] module-udev-detect.c: Ignoring /devices/platform/ff500000.usb/usb3/3-1/3-1:1.0/sound/card1, because marked so.
D: [pulseaudio] module-udev-detect.c: /dev/snd/controlC0 is accessible: yes
W: [pulseaudio] module-udev-detect.c: Failed to open /proc/asound/card0: No such file or directory
D: [pulseaudio] module-udev-detect.c: /devices/platform/sound/sound/card0 is busy: no
E: [pulseaudio] core-rtclock.c: Assertion 'clock_gettime(CLOCK_REALTIME, &ts) == 0' failed at ../src/pulsecore/core-rtclock.c:93, function pa_rtclock_get(). Aborting.
W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
D: [pulseaudio] core-rtclock.c: Timer slack is set to 50 us.
D: [pulseaudio] core-util.c: setpriority() worked.
I: [pulseaudio] core-util.c: Successfully gained nice level -11.
I: [pulseaudio] main.c: Found user 'root' (UID 0) and group 'root' (GID 0).
W: [pulseaudio] main.c: Home directory of user 'root' is not '/var/run/pulse', ignoring.
W: [pulseaudio] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
I: [pulseaudio] main.c: Successfully changed user to "root".
I: [pulseaudio] main.c: This is PulseAudio 14.2
D: [pulseaudio] main.c: Compilation CFLAGS: Not yet supported on meson
D: [pulseaudio] main.c: Running on host: Linux armv7l 5.10.16-rockchip #21.02.2 SMP PREEMPT Sun Feb 14 23:02:55 CET 2021
D: [pulseaudio] main.c: Found 4 CPUs.
I: [pulseaudio] main.c: Page size is 4096 bytes
D: [pulseaudio] main.c: Compiled with Valgrind support: no
D: [pulseaudio] main.c: Running in valgrind mode: no
D: [pulseaudio] main.c: Running in VM: no
D: [pulseaudio] main.c: Running from build tree: no
D: [pulseaudio] main.c: Optimized build: yes
D: [pulseaudio] main.c: All asserts enabled.
I: [pulseaudio] main.c: Machine ID is 4bb2d1b22b6b4897ab74971dd8ba1cf1.
I: [pulseaudio] main.c: Using runtime directory /var/run/pulse.
I: [pulseaudio] main.c: Using state directory /data/states.
I: [pulseaudio] main.c: Using modules directory /usr/lib/pulse-14.2/modules.
I: [pulseaudio] main.c: Running in system mode: yes
W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please make sure that you actually do want to do that.
W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.
W: [pulseaudio] pid.c: Stale PID file, overwriting.
I: [pulseaudio] main.c: System supports high resolution timers
D: [pulseaudio] memblock.c: Using private memory pool with 1024 slots of size 64.0 KiB each, total size is 64.0 MiB, maximum usable slot size is 65496
I: [pulseaudio] cpu-arm.c: CPU flags: V6 V7 VFP EDSP NEON VFPV3
I: [pulseaudio] svolume_arm.c: Initialising ARM optimized volume functions.
I: [pulseaudio] sconv_neon.c: Initialising ARM NEON optimized conversions.
I: [pulseaudio] mix_neon.c: Initialising ARM NEON optimized mixing functions.
I: [pulseaudio] remap_neon.c: Initialising ARM NEON optimized remappers.
D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-device-volumes.tdb'
I: [pulseaudio] database.c: Successfully opened 'device-volumes' database file '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-device-volumes.tdb'.
I: [pulseaudio] module.c: Loaded "module-device-restore" (index: #0; argument: "").
D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-stream-volumes.tdb'
I: [pulseaudio] database.c: Successfully opened 'stream-volumes' database file '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-stream-volumes.tdb'.
D: [pulseaudio] protocol-dbus.c: Interface org.PulseAudio.Ext.StreamRestore1 added for object /org/pulseaudio/stream_restore1
I: [pulseaudio] module.c: Loaded "module-stream-restore" (index: #1; argument: "").
D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-card-database.tdb'
I: [pulseaudio] database.c: Successfully opened 'card-database' database file '/data/states/4bb2d1b22b6b4897ab74971dd8ba1cf1-card-database.tdb'.
I: [pulseaudio] module.c: Loaded "module-card-restore" (index: #2; argument: "").
I: [pulseaudio] module.c: Loaded "module-switch-on-port-available" (index: #3; argument: "").
I: [pulseaudio] module.c: Loaded "module-switch-on-connect" (index: #4; argument: "").
D: [pulseaudio] module-udev-detect.c: Ignoring /devices/platform/ff500000.usb/usb3/3-1/3-1:1.0/sound/card1, because marked so.
D: [pulseaudio] module-udev-detect.c: /dev/snd/controlC0 is accessible: yes
W: [pulseaudio] module-udev-detect.c: Failed to open /proc/asound/card0: No such file or directory
D: [pulseaudio] module-udev-detect.c: /devices/platform/sound/sound/card0 is busy: no
E: [pulseaudio] core-rtclock.c: Assertion 'clock_gettime(CLOCK_REALTIME, &ts) == 0' failed at ../src/pulsecore/core-rtclock.c:93, function pa_rtclock_get(). Aborting.`

**Comment by Dominik-1980** [comment]
Here is the solution:

Download
https://github.com/moby/moby/blob/bc6f4cc7032544553d2304a5b47ba235dbfe5b9c/profiles/seccomp/default.json 5

copy this file to your raspberry into /etc/docker/

edit the file and replace in line 2 SCMP_ACT_ERRNO with SCMP_ACT_TRACE with the command

sudo nano /etc/docker/default.json
then

sudo nano /etc/docker/daemon.json
and add the following line:

„seccomp-profile“: „/etc/docker/default.json“,

between the two existing lines

restart the raspberry...

**Comment by Dominik-1980** [comment]
This is what it does:

The error “clock_gettime CLOCK_REALTIME failed” prompted me to check the system time inside the container. As I saw the strange output from the command “date” and I was pretty sure it have to has something to do with that.

As some of you confirmed me to have the same strange output, I began my research:

I think the developers uses alpine linux 3.13 on the last hassio_audio container.

I figured out, that in alpine 3.13 there was a change in a file called “musl” which uses new time64-compatible system calls that are not compatible with a library on the host system (raspbian in our case) which is called libseccomp.

musl 1.2 requires libseccomp at least 2.4.2 or greater. Raspbian still uses 2.3.3.

The fix in the docker daemon allows the container to fall back to 32-bit time system calls…

**Comment by nimamahmoudi** [comment]
I have the same issue with the same effects.

**Comment by JJFourie** [comment]
The steps provided by @Dominik-1980 is a (great!) workaround allowing us to continue to use our systems.
BUT
__***The root cause must be fixed within in the ```hassio_audio``` container.***__
It is not the role of the user community to hack around in their  *supported*  environments to fix this problem.
